name             'apt'
maintainer       'Thorsten Fischer'
maintainer_email 'thorsten@froschi.org'
license          'All rights reserved'
description      'Installs/Configures apt repos'
long_description 'Installs/Configures apt repos'
version          '0.2.0'
